### ISSUE TITLE
Case sensitivity issue: verifier vs. Verifier

### ISSUE THREAD

**Issue by julianboehm** [JacobEberhardt/decentralized-energy-trading#18]
When running `yarn migrate-contracts-authority` on the current `master` (abea7a7) the below error occurs.
My guess is that the script tries to import the contract from `zokrates-code/verifier.sol` (lower case), whereas the actual contract is named `Verifier` (upper case).
It is possible that Windows or certain Truffle versions are more tolerant in this regard.

be907d9 provides a working fix by changing `scripts/setup_zokrates.sh` to rename the lowercase `verifier.sol` to uppercase when copying to `contracts/`.
I'm not sure if there is a better solution, or if ZoKrates should be changed to generate an uppercase `Verifier.sol`.

```
2_deploy_contracts.js
=====================

/home/user/repo/node_modules/truffle/build/cli.bundled.js:170801
  throw new Error(
  ^

Error: Could not find artifacts for ../zokrates-code/verifier from any sources: [{"working_directory":"/home/user/repo","contracts_build_directory":"/home/user/repo/build/contracts"},{"working_directory":"/home/user/repo"},{},{"workingDirectory":"/home/user/repo","contractsBuildDirectory":"/home/user/repo/build/contracts"}]
    at Resolver.require (/home/user/repo/node_modules/truffle/build/webpack:/packages/resolver/index.js:37:1)
    at Object.require (/home/user/repo/node_modules/truffle/build/webpack:/packages/migrate/index.js:176:1)
    at ResolverIntercept.require (/home/user/repo/node_modules/truffle/build/cli.bundled.js:534850:32)
    at /home/user/repo/migrations/2_deploy_contracts.js:7:28
    at Script.runInContext (vm.js:131:20)
    at Script.runInNewContext (vm.js:137:17)
    at Object.file (/home/user/repo/node_modules/truffle/build/webpack:/packages/require/require.js:89:1)
    at Migration._load (/home/user/repo/node_modules/truffle/build/webpack:/packages/migrate/migration.js:40:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration.run (/home/user/repo/node_modules/truffle/build/webpack:/packages/migrate/migration.js:165:1)
Truffle v5.1.0 (core: 5.1.0)
Node v13.6.0
```

**Comment by petscheit** [comment]
I'm a bit confused why you have a `Verifier.sol` locally. By default ZoKrates exports the verifier as `verifier.sol` (lowercase) and it does so for me locally. 
One small problem in the verifier generation and deployment setup, is that `verifier.sol` is copied to `contracts/` in the `setup_zokrates.sh`, but in the deployment script, Truffle gets the contract from `zokrates-code/`. This shouldn't break anything though. 
What operating system are you running?

**Comment by julianboehm** [comment]
The generated file is `verifier.sol` (lowercase) for me too, the uppercase `Verifier` I mentioned refers to the `contract Verifier {...}` in `verifier.sol`, which when compiled results in the uppercase `build/contracts/Verifier.json`, which is why `2_deploy_contracts.js` can't find the lowercase `verifier.sol` when importing, I assume.
Changing the import from `../zokrates-code/verifier.sol` to `../contracts/verifier.sol` does not work either, it raises the same error.
Changing the import to the non-existing uppercase file `../zokrates-code/Verifier.sol` or `../contracts/Verifier.sol` *does work*, even though neither file exists on my disk.
I'm running Linux (5.4.6-arch3-1 x86_64).

**Comment by petscheit** [comment]
I see. What happens when you just import `artifacts.require("verifier")`? If that doesn't work I would propose we use your changes, but also changes the ZoKrates export-verifier step to create `Verifier.sol`, output can be changed with -o I believe
